meta_product_name: "Friendzy"
meta_title: "Friendzy - Keep in touch with your closests friends."
meta_description: "Encouraging face-to-face interaction with your closest friends"
meta_image: "Friendzy-link-image.jpg" # should exist in `app/assets/images/`
